Delete
WildCodeSchool/2022-09-RMT-JSCREW-Makesense pull request #113
Opened 2023-01-28 14:17 UTC by JoyMarkarian

2023-01-28 15:06 UTC, GuillaumeWernert submitted a review, later dismissed

2023-01-30 08:22 UTC, jujuck requested changes

2023-01-30 08:22 UTC, jujuck commented on frontend/src/pages/ShowOneDecision.jsx
> +// import Toast from "@components/Toast";
Pas de commentaire mort

2023-01-30 08:27 UTC, lesylv approved these changes

2023-01-30 09:15 UTC, jujuck approved these changes

2023-01-30 09:16 UTC, merged