New décision
WildCodeSchool/2022-09-RMT-JSCREW-Makesense pull request #12
Opened 2022-12-16 10:17 UTC by GuillaumeWernert

2022-12-16 10:23 UTC, KevinLavigne requested changes

2022-12-16 10:23 UTC, KevinLavigne commented on frontend/src/pages/NewDecision.jsx
> +    setHandleDecisionDate(e.target.value);
faire un seul state pour le formulaire

2022-12-16 12:55 UTC, BarzaGuignol approved these changes
OK pour moi

Par contre, pourquoi est-ce qu'il y a deux fichiers newDecision.css dont un de vide ?

2022-12-16 14:36 UTC, BarzaGuignol approved these changes
Nickel !

2022-12-19 13:36 UTC, ChristopherGchd approved these changes

2022-12-19 13:36 UTC, KevinLavigne approved these changes

2022-12-19 13:36 UTC, merged