Intégration d'un bouton pour créer une nouvelle prise de décision
WildCodeSchool/2022-09-RMT-JSCREW-Makesense pull request #29
Opened 2022-12-20 11:32 UTC by JoyMarkarian

2022-12-20 11:34 UTC, BarzaGuignol submitted a review, later dismissed
Ok pour moi

2022-12-20 13:19 UTC, lesylv submitted a review, later dismissed

2022-12-20 13:19 UTC, BarzaGuignol submitted a review, later dismissed

2022-12-20 13:46 UTC, jujuck requested changes

2022-12-20 13:46 UTC, jujuck commented on frontend/src/pages/AllDecisions.jsx
> +          <button
Pas de bouton dans un link

2022-12-20 13:49 UTC, lesylv submitted a review, later dismissed

2022-12-20 14:38 UTC, KevinLavigne submitted a review, later dismissed

2022-12-20 14:39 UTC, GuillaumeWernert approved these changes

2022-12-20 14:42 UTC, KevinLavigne approved these changes

2022-12-22 10:26 UTC, jujuck approved these changes

2022-12-22 10:26 UTC, merged