My advice
WildCodeSchool/2022-09-RMT-JSCREW-Makesense pull request #42
Opened 2023-01-04 15:20 UTC by BarzaGuignol

Fusion de la fonctionnalité créer mon avis vers branche dev

2023-01-04 16:22 UTC, ChristopherGchd approved these changes

2023-01-05 13:24 UTC, jujuck approved these changes

2023-01-05 13:35 UTC, jujuck requested changes

2023-01-05 13:35 UTC, jujuck commented on backend/src/router.js
> +router.post("/decisionsMaking/advice", AdviceController.postAdvice);
route post (Revoir la doc API REST), ("decision/:id/advice"), pas de verbe d'action

2023-01-05 16:20 UTC, BarzaGuignol commented on backend/src/router.js
> +router.post("/decisionsMaking/advice", AdviceController.postAdvice);
résolu

2023-01-05 16:26 UTC, ChristopherGchd approved these changes

2023-01-06 08:29 UTC, jujuck requested changes

2023-01-06 08:29 UTC, jujuck commented on frontend/src/pages/MyAdvice.jsx
> +      .post(`/decision/advice`, myAdviceText)
Et quoi après le POST, Rien. Il faut gérer la réponse positive

2023-01-06 08:29 UTC, jujuck commented on backend/src/controllers/adviceController.js
> +        .sendStatus(201);
Sur un post de data, on va essayer de renvoyer les données complètes avec l'id inséré... Cela permettra à l'interface Front de réagir

2023-01-17 14:43 UTC, BarzaGuignol commented on frontend/src/pages/MyAdvice.jsx
> +      .post(`/decision/advice`, myAdviceText)
fait

2023-01-17 15:08 UTC, BarzaGuignol commented on backend/src/controllers/adviceController.js
> +        .sendStatus(201);
fait

2023-01-17 15:35 UTC, KevinLavigne submitted a review, later dismissed

2023-01-17 15:38 UTC, ChristopherGchd submitted a review, later dismissed

2023-01-17 15:41 UTC, ChristopherGchd submitted a review, later dismissed

2023-01-17 15:43 UTC, KevinLavigne submitted a review, later dismissed

2023-01-18 14:03 UTC, closed without merging