Création des composants DecisionCard et DecisionList et de la page Al…
WildCodeSchool/2022-09-RMT-JSCREW-Makesense pull request #9
Opened 2022-12-15 10:42 UTC by JoyMarkarian

…lDecisions

2022-12-15 14:20 UTC, BarzaGuignol submitted a review, later dismissed
OK pour moi

2022-12-15 15:06 UTC, jujuck requested changes

2022-12-15 15:06 UTC, jujuck commented on frontend/src/components/DecisionInProgressList.jsx
> +    fetch(`${import.meta.env.VITE_BACKEND_URL}/decisionsMaking/?status=1`)
Le 1 (id) doit venir en props pour le rendre customisable

2022-12-15 15:06 UTC, jujuck commented on frontend/src/components/FirstDecisionList.jsx
> +import { useState, useEffect } from "react";
Fichier inutile, custom le avec une id en props

2022-12-15 15:06 UTC, jujuck commented on frontend/src/pages/AllDecisions.jsx
> +      <DecisionInProgressList />
Utilise le même fichier avec une props

2022-12-15 16:09 UTC, GuillaumeWernert approved these changes

2022-12-16 08:26 UTC, jujuck approved these changes

2022-12-16 08:26 UTC, merged